# Generated by Django 5.2.3 on 2025-06-16 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('DateOfJoining', models.DateField()),
                ('Contact', models.CharField(max_length=15)),
                ('IsActive', models.BooleanField(default=True)),
                ('DepartmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apibackendapp.department')),
            ],
        ),
    ]
