# Generated by Django 5.2.3 on 2025-06-16 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0003_userdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='DateOfJoining',
            new_name='Dateofjoining',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='IsActive',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Contact',
        ),
        migrations.AlterField(
            model_name='employee',
            name='DepartmentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='apibackendapp.department'),
        ),
    ]
